INSERT INTO user (id, username, password, name)
VALUES (1, 'mjordan@gmail.com',  'mjordanpassword', 'Michael Jordan'),
       (2, 'mjackson@gmail.com',  'mjacksonpassword', 'Michael Jackson'),
       (3, 'mscott@gmail.com',  'mscottpassword', 'Michael Scott'),
       (4, 'asab@gmail.com',  'asabpassword', 'Arvydas Sabonis'),
       (5, 'tsab@gmail.com',  'tsabpassword', 'Tautvydas Sabonis'),
       (6, 'dsab@gmail.com',  'dsabpassword', 'Domantas Sabonis'),
       (7, 'am@gmail.com',  'ampassword', 'Arvydas Macijauskas'),
       (8, 'manp@gmail.com',  'manppassword', 'Mantas Petruškevičius'),
       (9, 'god@gmail.com',  'godppassword', 'Goda Sabutytė-Alijeva'),
       (10, 'kar@gmail.com',  'karppassword', 'Karina Krysko'),
       (11, 'lk@gmail.com',  'lkppassword', 'Linas Karalius'),
       (12, 'id@gmail.com',  'idppassword', 'Ingeborga Dapkūnaitė'),
       (13, 'ival@gmail.com',  'ivalppassword', 'Inga Valinskienė'),
       (14, 'aval@gmail.com',  'avalppassword', 'Arūnas Valinskas'),
       (15, 'sjas@gmail.com',  'sjasppassword', 'Šarūnas Jasikevičius'),
       (16, 'smar@gmail.com',  'smarppassword', 'Šarūnas Marčiulionis'),
       (17, 'manjan@gmail.com',  'manjanppassword', 'Mantas Jankavičius'),
       (18, 'jusjan@gmail.com',  'jusjanppassword', 'Justinas Jankevičius'),
       (19, 'vikcmi@gmail.com',  'vikcmippassword', 'Viktorija Čmilytė Nielsen'),
       (20, 'ros@gmail.com',  'rospassword', 'Rosita Čivilytė'),
       (21, 'isim@gmail.com', 'isimpassword', 'Ingrida Šimonytė'),
       (22, 'aa@gmail.com', 'aapassword', 'Aušrinė Armonaitė'),
       (23, 'aa@gmail.com', 'aapassword', 'Kasabas Sabutsabersab'),
        (24, 'ss@gmail.com', 'sspassword', 'Sabina Sabinienė');